language: node_js
node_js:
  - "9"

script:
  - npm test

after_success:
    - npm install -g ci-publish
    - ci-publish || true
deploy:
  provider: releases
  api_key: $RELEASE_API_TOKEN
  skip_cleanup: true
  on:
    repo: zerosuxx/zerojs-di
    tags: true
